# Generated by Django 6.1.1 on 2026-09-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_requirements', models.JSONField(default=list)),
                ('financial_requirements', models.JSONField(default=dict)),
                ('technical_requirements', models.JSONField(default=list)),
                ('experience_requirements', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('deadlines', models.JSONField(default=list)),
                ('penalties', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Intelligence', to='tenders.tender')),
            ],
        ),
    ]
