# Generated by Django 6.1.1 on 2026-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tenderintelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderintelligence',
            name='project_duration',
            field=models.JSONField(default=list),
        ),
    ]
