# Generated by Django 6.1.1 on 2026-09-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tenderintelligence_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderintelligence',
            name='project_duration',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
