# Generated by Django 6.1.1 on 2026-09-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_alter_tenderintelligence_project_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidReadinessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_requirements', models.JSONField(default=list)),
                ('missing_requirements', models.JSONField(default=list)),
                ('critical_missing_requirements', models.JSONField(default=list)),
                ('score', models.PositiveIntegerField()),
                ('readiness', models.CharField(max_length=20)),
                ('bid_ready', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_Readiness_analyses', to='tenders.tender')),
            ],
        ),
    ]
