# Generated by Django 6.1.1 on 2026-09-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_annual_turnover_and_more'),
        ('tenders', '0005_bidreadinessanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidreadinessanalysis',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_readiness_analyses', to='companies.companyprofile'),
        ),
    ]
