# Generated by Django 6.1.1 on 2026-09-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_annual_turnover_and_more'),
        ('tenders', '0006_bidreadinessanalysis_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidreadinessanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_readiness_analyses', to='companies.companyprofile'),
        ),
    ]
