# Generated by Django 6.1.1 on 2026-09-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_annual_turnover_and_more'),
        ('tenders', '0007_alter_bidreadinessanalysis_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('critical_blockers', models.JSONField(default=list)),
                ('priority_actions', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_analyses', to='companies.companyprofile')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_analyses', to='tenders.tender')),
            ],
        ),
    ]
