# Generated by Django 6.1.1 on 2026-09-08 10:33

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('page', models.PositiveIntegerField()),
                ('chunk_id', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('test', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
