# Generated by Django 6.1.1 on 2026-09-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchunk',
            old_name='test',
            new_name='text',
        ),
    ]
